# Generated by Django 4.2.9 on 2024-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите адрес электронной почты",
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
    ]
