# Generated by Django 4.2.9 on 2024-11-02 10:15

import cryptocurrencies.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название криптовалюты",
                        max_length=100,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Криптовалюта",
                "verbose_name_plural": "Криптовалюты",
            },
        ),
        migrations.CreateModel(
            name="Constituent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Укажите вес криптовалюты в процентах",
                        max_digits=10,
                        validators=[cryptocurrencies.validators.validate_percentage],
                        verbose_name="вес в процентах",
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        help_text="Укажите криптовалюту",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptocurrencies.cryptocurrency",
                        verbose_name="криптовалюта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав индекса CCI30",
                "verbose_name_plural": "Состав индекса CCI30",
                "unique_together": {("date", "cryptocurrency", "weight")},
            },
        ),
    ]
