# Generated by Django 4.2.9 on 2024-11-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptocurrencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constituent",
            name="date",
            field=models.DateField(help_text="Укажите дату", verbose_name="дата"),
        ),
    ]
