# Generated by Django 4.2.9 on 2024-11-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptocurrencies", "0002_alter_constituent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="cmc_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="CoinMarketCap ID"
            ),
        ),
        migrations.AddField(
            model_name="cryptocurrency",
            name="cmc_rank",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ранг на CoinMarketCap"
            ),
        ),
        migrations.AddField(
            model_name="cryptocurrency",
            name="symbol",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="CoinMarketCap символ",
            ),
        ),
    ]
