# Generated by Django 4.2.9 on 2024-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptocurrencies", "0004_ccprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccprice",
            name="last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время последнего обновления"
            ),
        ),
    ]
