# Generated by Django 4.2.9 on 2024-11-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptocurrencies", "0005_alter_ccprice_last_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ccprice",
            options={
                "ordering": ["-last_updated"],
                "verbose_name": "Цена криптовалюты в USD",
                "verbose_name_plural": "Цены криптовалют в USD",
            },
        ),
    ]
